test-ci::ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -16,8 +16,8 @@ workflow:
     - if: $CI_COMMIT_MESSAGE =~ /(^|,)test-ci::infra(,|$)/
 
 # include templates
-#include:
-#  - local: '/.gitlab-ci/templates.yml'
+include:
+  - local: '/.gitlab-ci/templates.yml'
 
 #stages:
 #  - smoke tests
@@ -55,6 +55,7 @@ variables:
     - bigbang
     - dogfood
     - generic
+
 .bigbang:
   image: registry.dso.mil/platform-one/big-bang/pipeline-templates/pipeline-templates/k8s-ci:v1.20.4-bb.3
   extends: .gitlab-runner-tags
@@ -85,95 +86,95 @@ pre vars:
 ##-----------------------------------------------------------------------------------------------------------------------
 ## Smoke Tests
 ##
-#
-#.chart_changes: &chart_changes
-#  changes:
-#    - chart/**/*
-#    - .gitlab-ci.yml
-#    - .gitlab-ci/jobs/**/*
-#    - scripts/**/*
-#    - tests/**/*
-#    - base/flux/*
-#
-#.deploy_bigbang: &deploy_bigbang
-#  - |
-#    set -e
-#    for deploy_script in $(find ./scripts/deploy -type f -name '*.sh' | sort); do
-#      chmod +x ${deploy_script}
-#      echo "Executing ${deploy_script}..."
-#      ./${deploy_script}
-#    done
-#
-#.test_bigbang: &test_bigbang
-#  - |
-#    set -e
-#    for test_script in $(find ./tests -type f -name '*.sh' | sort); do
-#      chmod +x ${test_script}
-#      echo "Executing ${test_script}..."
-#      ./${test_script}
-#    done
-#
-#clean install:
-#  stage: smoke tests
-#  extends:
-#    - .k3d-ci
-#  variables:
-#    CLUSTER_NAME: "clean-${CI_COMMIT_SHORT_SHA}"
-#  rules:
-#    - if: '($CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master") || $CI_MERGE_REQUEST_LABELS =~ /(^|,)test-ci::infra(,|$)/'
-#      when: never
-#    - *chart_changes
-#  script:
-#    - *deploy_bigbang
-#    - *test_bigbang
-#
-#    # Fetch list of all images ran (retry crictl up to 6x)
-#    - cid=$(docker ps -aqf "name=k3d-${CI_JOB_ID}-server-0")
-#    - images=$(timeout 65 bash -c "until docker exec $cid crictl images -o json; do sleep 10; done;")
-#    - echo $images | jq -r '.images[].repoTags[0] | select(. != null)' | tee images.txt
-#  artifacts:
-#    paths:
-#      - images.txt
-#      - "cypress-tests/*/tests/cypress/screenshots"
-#      - "cypress-tests/*/tests/cypress/videos"
-#    expire_in: 7 days
-#    when: always
-#
-#upgrade:
-#  stage: smoke tests
-#  dependencies:
-#    - pre vars
-#  extends:
-#    - .k3d-ci
-#  rules:
-#    # skip job for nightly master and "test-ci::infra" labeled pipelines
-#    - if: '($CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master") || $CI_MERGE_REQUEST_LABELS =~ /(^|,)test-ci::infra(,|$)/'
-#      when: never
-#    # skip job when MR title starts with 'SKIP UPGRADE'
-#    - if: '$CI_MERGE_REQUEST_TITLE =~ /^SKIP UPGRADE/'
-#      when: never
-#    # run pipeline on merge request events
-#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-#      <<: *chart_changes
-#  variables:
-#    CLUSTER_NAME: "upgrade-${CI_COMMIT_SHORT_SHA}"
-#  script:
-#    - echo "Install Big Bang from ${CI_DEFAULT_BRANCH}"
-#    - git fetch && git checkout ${CI_DEFAULT_BRANCH}
-#    - *deploy_bigbang
-#    - *test_bigbang
-#    - echo "Upgrade Big Bang from ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
-#    - git reset --hard && git clean -fd
-#    - git checkout ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
-#    - *deploy_bigbang
-#    - *test_bigbang
-#  artifacts:
-#    paths:
-#      - "cypress-tests/*/tests/cypress/screenshots"
-#      - "cypress-tests/*/tests/cypress/videos"
-#    expire_in: 7 days
-#    when: always
-#
+
+.chart_changes: &chart_changes
+  changes:
+    - chart/**/*
+    - .gitlab-ci.yml
+    - .gitlab-ci/jobs/**/*
+    - scripts/**/*
+    - tests/**/*
+    - base/flux/*
+
+.deploy_bigbang: &deploy_bigbang
+  - |
+    set -e
+    for deploy_script in $(find ./scripts/deploy -type f -name '*.sh' | sort); do
+      chmod +x ${deploy_script}
+      echo "Executing ${deploy_script}..."
+      ./${deploy_script}
+    done
+
+.test_bigbang: &test_bigbang
+  - |
+    set -e
+    for test_script in $(find ./tests -type f -name '*.sh' | sort); do
+      chmod +x ${test_script}
+      echo "Executing ${test_script}..."
+      ./${test_script}
+    done
+
+clean install:
+  stage: smoke tests
+  extends:
+    - .k3d-ci
+  variables:
+    CLUSTER_NAME: "clean-${CI_COMMIT_SHORT_SHA}"
+  rules:
+    - if: '($CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master") || $CI_MERGE_REQUEST_LABELS =~ /(^|,)test-ci::infra(,|$)/'
+      when: never
+    - *chart_changes
+  script:
+    - *deploy_bigbang
+    - *test_bigbang
+
+    # Fetch list of all images ran (retry crictl up to 6x)
+    - cid=$(docker ps -aqf "name=k3d-${CI_JOB_ID}-server-0")
+    - images=$(timeout 65 bash -c "until docker exec $cid crictl images -o json; do sleep 10; done;")
+    - echo $images | jq -r '.images[].repoTags[0] | select(. != null)' | tee images.txt
+  artifacts:
+    paths:
+      - images.txt
+      - "cypress-tests/*/tests/cypress/screenshots"
+      - "cypress-tests/*/tests/cypress/videos"
+    expire_in: 7 days
+    when: always
+
+upgrade:
+  stage: smoke tests
+  dependencies:
+    - pre vars
+  extends:
+    - .k3d-ci
+  rules:
+    # skip job for nightly master and "test-ci::infra" labeled pipelines
+    - if: '($CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "master") || $CI_MERGE_REQUEST_LABELS =~ /(^|,)test-ci::infra(,|$)/'
+      when: never
+    # skip job when MR title starts with 'SKIP UPGRADE'
+    - if: '$CI_MERGE_REQUEST_TITLE =~ /^SKIP UPGRADE/'
+      when: never
+    # run pipeline on merge request events
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+      <<: *chart_changes
+  variables:
+    CLUSTER_NAME: "upgrade-${CI_COMMIT_SHORT_SHA}"
+  script:
+    - echo "Install Big Bang from ${CI_DEFAULT_BRANCH}"
+    - git fetch && git checkout ${CI_DEFAULT_BRANCH}
+    - *deploy_bigbang
+    - *test_bigbang
+    - echo "Upgrade Big Bang from ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
+    - git reset --hard && git clean -fd
+    - git checkout ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
+    - *deploy_bigbang
+    - *test_bigbang
+  artifacts:
+    paths:
+      - "cypress-tests/*/tests/cypress/screenshots"
+      - "cypress-tests/*/tests/cypress/videos"
+    expire_in: 7 days
+    when: always
+
 ##-----------------------------------------------------------------------------------------------------------------------
 #
 ##-----------------------------------------------------------------------------------------------------------------------
@@ -213,7 +214,7 @@ pre vars:
 #
 #aws/network up:
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra fork
 #    - .network up
 #  environment:
@@ -222,7 +223,7 @@ pre vars:
 #
 #aws/network down:
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra cleanup
 #    - .network down
 #  stage: network down
@@ -240,7 +241,7 @@ pre vars:
 #aws/rke2/cluster up:
 #  stage: cluster up
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra create
 #    - .rke2 up
 #  needs:
@@ -254,7 +255,7 @@ pre vars:
 #aws/rke2/bigbang up:
 #  stage: bigbang up
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra create
 #    - .bigbang
 #  needs:
@@ -275,7 +276,7 @@ pre vars:
 #aws/rke2/bigbang test:
 #  stage: test
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra create
 #    - .bigbang
 #  needs:
@@ -298,7 +299,7 @@ pre vars:
 #aws/rke2/bigbang down:
 #  stage: bigbang down
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra cleanup
 #    - .bigbang
 #  needs:
@@ -319,7 +320,7 @@ pre vars:
 #aws/rke2/cluster down:
 #  stage: cluster down
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #    - .infra cleanup
 #    - .rke2 down
 #  needs:
@@ -339,7 +340,7 @@ pre vars:
 #  stage: package
 #  image: registry.dso.mil/platform-one/big-bang/bigbang/synker:0.0.3
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #  rules:
 #    # run job for manual tag events or test-ci::release MRs
 #    - if: '$CI_COMMIT_TAG || $CI_MERGE_REQUEST_LABELS =~ /(^|,)test-ci::release(,|$)/'
@@ -387,7 +388,7 @@ pre vars:
 #  stage: release
 #  image: registry.gitlab.com/gitlab-org/release-cli:latest
 #  extends:
-#    - .bigbang-dogfood
+#    - .gitlab-runner-tags
 #  rules:
 #    # run job for manual tag events or test-ci::release MRs
 #    - if: '$CI_COMMIT_TAG || $CI_MERGE_REQUEST_LABELS =~ /(^|,)test-ci::release(,|$)/'
